### ISSUE TITLE
mapi_erase is very slow

### ISSUE THREAD

**Issue by bluddy** [fredrikwidlund/libdynamic#2]
We use your code for our system (K3), and so far have gotten great performance boosts out of it. I just tried switching my data structures from C++'s std::unordered_map to mapi's, and even though it worked for other uses, performance was really bad. perf showed that mapi_erase is very slow since it must shift the whole array with every erase. Is there any way to improve this?

**Comment by fredrikwidlund** [comment]
Thanks!

There are two typical strategies that can be used for removal, marking a slot as 'deleted' rather than 'free' which can result in a polluted hash table with some bad edge cases, or shifting used entries to fill up deleted slots. Both strategies have, of course, pros and cons.

I'm guessing you are testing by inserting an increasing sequence integers and then erasing, which distributes values very badly (actually not at all), resulting in the behaviour you are seeing. What takes time in your case is likely not shifting the array, but rather going through it to find the last empty slot. 

If your real use case actually uses a sequence of integers without gaps, then use a hash function to distribute them better (http://burtleburtle.net/bob/hash/integer.html), and you will find that the behaviour you tested goes away completely (Make sure to filter out the <empty key> -1). If your test case doesn't reflect on your actual use case it could be that the distribution is good enough using the identity hash.

The alternative is using a deleted slot status, which mapi did until a few commits ago when I changed it to use current strategy. 

If this doesn't answer your question, then please describe your use case more in detail!

**Comment by fredrikwidlund** [comment]
Given some time I will add integer hashing that will fix this. Did some performance tests and the overhead that this implies is not that great.

**Comment by bluddy** [comment]
Thank you for replying. 

My use case is indeed an increasing, near-contiguous sequence of integer keys (versions), with consecutive inserts followed by random deletes. Now that I took the time to read the imap code in-depth, I see that there's no hashing going on at all by default, which indeed explains the problem. I think some hashing is probably a good idea. I'll add it on my end and see if it fixes the problem.
